FROM vault:1.3.3

ADD files-vault /opt/files/

RUN chmod +x /opt/files/setup.sh
RUN /opt/files/setup.sh

ENV SKIP_SETCAP=1
ENV VAULT_ADDR=http://0.0.0.0:8200

ENTRYPOINT ["/opt/files/run.sh"]
CMD ["server", "-dev"]
HEALTHCHECK --interval=5s --timeout=2s \
  CMD [[ -f /opt/healthcheck ]]
